import { createRolloutTrackerMount } from '/rollout-tracker-client.js';

export const id = "update-break-glass-accounts-mfa-tracker";
export const label = "Update Break Glass Accounts & MFA";

// Generated by Rollout Tracker Builder -- see
// @dashboard/shell/public/rollout-tracker-client.js for the actual
// grid/status-editing mechanism, shared by every tracker built this way.
export const mount = createRolloutTrackerMount({
  id,
  label,
  apiBase: "/api/update-break-glass-accounts-mfa-tracker",
  rowNoun: "Client",
});
