import { createTabbedPageMount } from '/tab-page-client.js';

export const id = "client-tabs";
export const label = "CLIENT";

// Generated by Tab Page Builder -- see @dashboard/shell/tab-page-client.js
// for the actual tabbed-page mechanism, shared by every tabbed page on
// this dashboard.
export const mount = createTabbedPageMount({
  id,
  label,
  apiBase: "/api/client-tabs",
  defaultTabs: [{"id":"check-client","label":"Check Client"},{"id":"client-activity","label":"Client Activity"},{"id":"client-financials","label":"Client Financials"},{"id":"client-info-tabs","label":"Client Info"},{"id":"client-summary","label":"Client Summary"},{"id":"contract-services","label":"Contract Services"},{"id":"contract-services-update-contracts","label":"Contract Services"},{"id":"m365-environment","label":"M365 Environment"}],
});
