// Permanent-tabs and help-text GET/PUT for this one tabbed page --
// see @dashboard/shell/tab-page-server.js for the actual
// implementation (shared by every tabbed page on this dashboard).
// Generated by Tab Page Builder.
module.exports = require('@dashboard/shell/tab-page-server.js').createTabPageRouter(__dirname);
