import { createRolloutTrackerMount } from '/rollout-tracker-client.js';

export const id = "test-tracker-tracker";
export const label = "Test Tracker";

// Generated by Rollout Tracker Builder -- see
// @dashboard/shell/public/rollout-tracker-client.js for the actual
// grid/status-editing mechanism, shared by every tracker built this way.
export const mount = createRolloutTrackerMount({
  id,
  label,
  apiBase: "/api/test-tracker-tracker",
  rowNoun: "Thing to track",
});
