// Generic rollout-tracker grid API for this one tracker -- see
// @dashboard/shell/rollout-tracker-server.js for the actual
// implementation (shared by every tracker built this way).
// Generated by Rollout Tracker Builder.
module.exports = require('@dashboard/shell/rollout-tracker-server.js').createRolloutTrackerRouter(__dirname, { rowNoun: "Thing to track" });
