const express = require('express');
const fs = require('fs');
const path = require('path');
const { registerPage, pages, readNavLayout, writeNavLayout, isDashboardAdmin } = require('@dashboard/shell/registry.js');

// Same directory shell/registry.js's own discoverPages() scans -- this
// package sits alongside every other page package, one level up from here.
const packagesRoot = path.resolve(__dirname, '..');

// Hyphenated, matching this dashboard's own `id` convention -- same as
// External Page Builder's own slugify(), duplicated rather than shared
// since it's three lines and pulling in a whole extra require for it
// isn't worth it.
function slugify(label) {
  return label
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Same "array of lines, not one big template literal" technique External
// Page Builder's own buildClientJs() uses -- keeps which parts are
// literal OUTPUT text versus evaluated NOW unambiguous, rather than
// fighting nested backtick/${} escaping.
function buildClientJs(slug, label, defaultTabs) {
  const lines = [
    "import { createTabbedPageMount } from '/tab-page-client.js';",
    '',
    `export const id = ${JSON.stringify(slug)};`,
    `export const label = ${JSON.stringify(label)};`,
    '',
    '// Generated by Tab Page Builder -- see @dashboard/shell/tab-page-client.js',
    '// for the actual tabbed-page mechanism, shared by every tabbed page on',
    '// this dashboard.',
    'export const mount = createTabbedPageMount({',
    '  id,',
    '  label,',
    `  apiBase: ${JSON.stringify(`/api/${slug}`)},`,
    `  defaultTabs: ${JSON.stringify(defaultTabs)},`,
    '});',
    '',
  ];
  return lines.join('\n');
}

function buildServerJs() {
  return [
    '// Permanent-tabs and help-text GET/PUT for this one tabbed page --',
    '// see @dashboard/shell/tab-page-server.js for the actual',
    '// implementation (shared by every tabbed page on this dashboard).',
    '// Generated by Tab Page Builder.',
    "module.exports = require('@dashboard/shell/tab-page-server.js').createTabPageRouter(__dirname);",
    '',
  ].join('\n');
}

function buildPackageJson(slug, label) {
  return (
    JSON.stringify(
      {
        name: `@dashboard/${slug}`,
        version: '1.0.0',
        private: true,
        main: 'server.js',
        dashboardPage: {
          id: slug,
          label,
          client: 'client.js',
          server: 'server.js',
          // No restrictedTo -- a tabbed page is meant for everyone to
          // use; only ITS management (making a tab permanent, renaming
          // the page) is admin-gated, same as every other tabbed page.
          tabbed: true,
        },
        dependencies: {
          '@dashboard/shell': '*',
          express: '^4.19.2',
        },
      },
      null,
      2
    ) + '\n'
  );
}

const router = express.Router();
router.use(express.json());

router.post('/publish', (req, res) => {
  try {
    // Creating a whole new tabbed page is the "add" capability -- by
    // request, admin-only, same as making a tab permanent on an
    // existing one.
    if (!isDashboardAdmin(req)) {
      return res.status(403).json({ error: 'Only Amber can create a new tabbed page.' });
    }

    const label = (req.body?.label || '').trim();
    const tabIds = Array.isArray(req.body?.tabIds) ? req.body.tabIds : [];
    if (!label) return res.status(400).json({ error: 'Page name is required.' });
    if (tabIds.length === 0) return res.status(400).json({ error: 'Pick at least one starting tab.' });

    // Resolve each chosen id to its real, currently-registered label --
    // never trust a label the client might have sent, and silently drop
    // any id that isn't a real page (a stale selection from before a
    // page was removed, say) rather than hardcoding something bogus into
    // a page every viewer will load.
    const defaultTabs = [];
    for (const tabId of tabIds) {
      const page = pages.find((p) => p.id === tabId);
      if (page) defaultTabs.push({ id: page.id, label: page.label });
    }
    if (defaultTabs.length === 0) return res.status(400).json({ error: 'None of the selected tabs are real pages.' });

    // "-tabs" suffix, not just the plain slug -- keeps a tabbed page's id
    // visually distinct from the real page(s) it contains (e.g.
    // "client-info-tabs" next to "client-info", the category it mirrors),
    // same convention every hand-built tabbed page already follows.
    const slug = `${slugify(label)}-tabs`;
    if (slug === '-tabs') return res.status(400).json({ error: 'Page name must contain at least one letter or number.' });

    const pageDir = path.join(packagesRoot, slug);
    // Covers both "a package with this id genuinely already exists on
    // disk" and "this process already registered it this session but
    // hasn't been restarted yet".
    if (fs.existsSync(pageDir) || pages.some((p) => p.id === slug)) {
      return res.status(409).json({ error: `A page named "${label}" (id "${slug}") already exists. Pick a different name.` });
    }

    fs.mkdirSync(pageDir);
    fs.writeFileSync(path.join(pageDir, 'package.json'), buildPackageJson(slug, label));
    fs.writeFileSync(path.join(pageDir, 'client.js'), buildClientJs(slug, label, defaultTabs));
    fs.writeFileSync(path.join(pageDir, 'server.js'), buildServerJs());

    // Makes it immediately servable AND mounts its own /api/<id> router
    // (its permanent-tabs GET/PUT) -- see registerPage()'s own comment in
    // registry.js for why a page with its own server.js now works
    // exactly the same as one that existed at boot, no restart needed.
    registerPage({
      dir: slug,
      root: pageDir,
      id: slug,
      label,
      client: 'client.js',
      server: 'server.js',
      tabbed: true,
    });

    // Lands at the root of the sidebar, by request -- same as Ticket
    // Info Tabs and every other hand-built tabbed page. Dragged into
    // place later via the existing localhost-only nav editor.
    const tree = readNavLayout() || [];
    tree.push({ type: 'page', id: slug });
    writeNavLayout(tree);

    res.json({ id: slug, label });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
