const express = require('express');
const fs = require('fs');
const path = require('path');
const { registerPage, pages, readNavLayout, writeNavLayout } = require('@dashboard/shell/registry.js');

// Same directory shell/registry.js's own discoverPages() scans -- this
// package sits alongside every other page package, one level up from here.
const packagesRoot = path.resolve(__dirname, '..');

// Restricted to Amber only, same as this page itself (see package.json's
// dashboardPage.restrictedTo) -- every page this tool generates inherits
// that same allowlist, since a freshly-published page always lands in the
// Amber-only Testing category first (by request) and she opens it up
// herself once she's happy with it.
const GENERATED_PAGE_RESTRICTED_TO = ['amber@ambientit.com.au'];

// Hyphenated, matching this dashboard's own `id` convention (rewst-form-test,
// check-client, ...) -- NOT the underscore-based slugify() TC Elite Rollout
// uses for its own column keys, which is a different, unrelated convention.
function slugify(label) {
  return label
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function htmlAttrEscape(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Exact same shape as the hand-written rewst-form-test/client.js (no
// server-side logic at all, just a labeled iframe) -- built as an array of
// plain lines, not one big template literal, so which parts are literal
// OUTPUT text (single/double-quoted, e.g. the `${EMBED_URL}` the generated
// file interpolates at ITS OWN runtime) versus evaluated NOW (backtick
// lines) stays unambiguous rather than fighting nested backtick escaping.
function buildClientJs(slug, label, url) {
  const lines = [
    `export const id = ${JSON.stringify(slug)};`,
    `export const label = ${JSON.stringify(label)};`,
    '',
    '// Generated by External Page Builder -- a plain iframe embed, same',
    '// pattern as rewst-form-test/technician-forms (no server-side logic).',
    `const EMBED_URL = ${JSON.stringify(url)};`,
    '',
    'export function mount(container) {',
    '  container.innerHTML = `',
    '    <iframe',
    '      src="${EMBED_URL}"',
    `      title="${htmlAttrEscape(label)}"`,
    '      class="embedded-frame"',
    '    ></iframe>',
    '  `;',
    '}',
    '',
  ];
  return lines.join('\n');
}

function buildPackageJson(slug, label) {
  return (
    JSON.stringify(
      {
        name: `@dashboard/${slug}`,
        version: '1.0.0',
        private: true,
        main: 'client.js',
        dashboardPage: {
          id: slug,
          label,
          client: 'client.js',
          restrictedTo: GENERATED_PAGE_RESTRICTED_TO,
          // Every page this tool generates is, by definition, a direct
          // embed of an outside site -- flags it in the sidebar with the
          // same small "external" icon Automation Forms/Rewst Form Test
          // use (see app.js's renderPageItem()), by request.
          external: true,
        },
      },
      null,
      2
    ) + '\n'
  );
}

function findCategory(tree, categoryId) {
  return (tree || []).find((node) => node.type === 'category' && node.id === categoryId);
}

const router = express.Router();
router.use(express.json());

router.post('/publish', (req, res) => {
  try {
    const label = (req.body?.label || '').trim();
    const url = (req.body?.url || '').trim();
    if (!label) return res.status(400).json({ error: 'Page name is required.' });
    if (!url) return res.status(400).json({ error: 'URL to embed is required.' });
    if (!/^https?:\/\//i.test(url)) return res.status(400).json({ error: 'URL must start with http:// or https://.' });
    try {
      new URL(url); // throws on a genuinely malformed URL, beyond just the scheme check above
    } catch {
      return res.status(400).json({ error: 'That does not look like a valid URL.' });
    }

    const slug = slugify(label);
    if (!slug) return res.status(400).json({ error: 'Page name must contain at least one letter or number.' });

    const pageDir = path.join(packagesRoot, slug);
    // Covers both "a package with this id genuinely already exists on
    // disk" and "this process already registered it this session but
    // hasn't been restarted yet" -- either way, publishing again under the
    // same name would silently clobber files client.js already wrote.
    if (fs.existsSync(pageDir) || pages.some((p) => p.id === slug)) {
      return res.status(409).json({ error: `A page named "${label}" (id "${slug}") already exists. Pick a different name.` });
    }

    fs.mkdirSync(pageDir);
    fs.writeFileSync(path.join(pageDir, 'package.json'), buildPackageJson(slug, label));
    fs.writeFileSync(path.join(pageDir, 'client.js'), buildClientJs(slug, label, url));

    // Makes it immediately servable -- /pages-registry.js and
    // /pages/:id/client.js in shell/server.js both read this same `pages`
    // array fresh on every request, so no restart is needed. See
    // registry.js's own comment for the full reasoning.
    registerPage({
      dir: slug,
      root: pageDir,
      id: slug,
      label,
      client: 'client.js',
      restrictedTo: GENERATED_PAGE_RESTRICTED_TO,
      external: true,
    });

    // Drops it straight into the Testing category, by request -- Amber
    // moves it into its real category herself later via the existing
    // localhost-only drag-and-drop nav editor. Falls back to a bare
    // top-level entry (same shape app.js's own reconcileTree() already
    // tolerates for an unplaced page) if "testing" is ever renamed/missing,
    // rather than silently failing to place the new page anywhere.
    const tree = readNavLayout() || [];
    const testingCategory = findCategory(tree, 'testing');
    if (testingCategory) {
      testingCategory.children.push({ type: 'page', id: slug });
    } else {
      tree.push({ type: 'page', id: slug });
    }
    writeNavLayout(tree);

    res.json({ id: slug, label });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
