const express = require('express');
const fs = require('fs');
const path = require('path');
const { registerPage, pages, readNavLayout, writeNavLayout } = require('@dashboard/shell/registry.js');
const { createRolloutTrackerDb } = require('@dashboard/shell/rollout-tracker-db.js');
const { TRACKERS_CATEGORY_ID, TRACKERS_CATEGORY_LABEL, movePageToCategory } = require('@dashboard/shell/rollout-tracker-nav.js');
const { isTrackerManager } = require('@dashboard/shell/rollout-tracker-permissions.js');

// Same directory shell/registry.js's own discoverPages() scans -- this
// package sits alongside every other page package, one level up from here.
const packagesRoot = path.resolve(__dirname, '..');

// Same slugify() convention as tab-page-builder/server.js -- duplicated
// rather than shared, it's three lines.
function slugify(label) {
  return label
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildClientJs(slug, trackerLabel, apiBase, rowNoun) {
  const lines = [
    "import { createRolloutTrackerMount } from '/rollout-tracker-client.js';",
    '',
    `export const id = ${JSON.stringify(slug)};`,
    `export const label = ${JSON.stringify(trackerLabel)};`,
    '',
    '// Generated by Rollout Tracker Builder -- see',
    '// @dashboard/shell/public/rollout-tracker-client.js for the actual',
    '// grid/status-editing mechanism, shared by every tracker built this way.',
    'export const mount = createRolloutTrackerMount({',
    '  id,',
    '  label,',
    `  apiBase: ${JSON.stringify(apiBase)},`,
    `  rowNoun: ${JSON.stringify(rowNoun)},`,
    '});',
    '',
  ];
  return lines.join('\n');
}

function buildServerJs(rowNoun) {
  return [
    '// Generic rollout-tracker grid API for this one tracker -- see',
    '// @dashboard/shell/rollout-tracker-server.js for the actual',
    '// implementation (shared by every tracker built this way).',
    '// Generated by Rollout Tracker Builder.',
    `module.exports = require('@dashboard/shell/rollout-tracker-server.js').createRolloutTrackerRouter(__dirname, { rowNoun: ${JSON.stringify(rowNoun)} });`,
    '',
  ].join('\n');
}

function buildPackageJson(slug, trackerLabel) {
  return (
    JSON.stringify(
      {
        name: `@dashboard/${slug}`,
        version: '1.0.0',
        private: true,
        main: 'server.js',
        dashboardPage: {
          id: slug,
          label: trackerLabel,
          client: 'client.js',
          server: 'server.js',
          // No restrictedTo -- using an already-created tracker (editing
          // cells, adding rows) is meant for the whole service team, same
          // as TC Elite Rollout itself; only creating a new one (this
          // builder's own /publish, below) and adding a COLUMN to one
          // (isDashboardAdmin() in rollout-tracker-server.js) are gated.
        },
        dependencies: {
          '@dashboard/shell': '*',
          express: '^4.19.2',
        },
      },
      null,
      2
    ) + '\n'
  );
}

const router = express.Router();
router.use(express.json());

// Lets client.js hide the publish form entirely for a non-manager rather
// than showing it and letting the actual POST /publish below 403 --
// same "server decides, client just reflects it" convention as
// rollout-tracker-server.js's own GET /'s isManager field.
router.get('/can-publish', (req, res) => {
  res.json({ isManager: isTrackerManager(req) });
});

router.post('/publish', (req, res) => {
  try {
    if (!isTrackerManager(req)) {
      return res.status(403).json({ error: 'Only a Tracker Manager can create a new rollout tracker.' });
    }

    const trackerLabel = (req.body?.label || '').trim();
    const rowNoun = (req.body?.rowNoun || '').trim() || 'Item';
    const rowNames = Array.isArray(req.body?.rowNames) ? req.body.rowNames.map((s) => String(s).trim()).filter(Boolean) : [];
    const columnLabels = Array.isArray(req.body?.columnLabels) ? req.body.columnLabels.map((s) => String(s).trim()).filter(Boolean) : [];

    if (!trackerLabel) return res.status(400).json({ error: 'Tracker name is required.' });
    if (rowNames.length === 0) return res.status(400).json({ error: `At least one ${rowNoun.toLowerCase()} is required.` });
    if (columnLabels.length === 0) return res.status(400).json({ error: 'At least one column is required.' });

    const slug = `${slugify(trackerLabel)}-tracker`;
    if (slug === '-tracker') return res.status(400).json({ error: 'Tracker name must contain at least one letter or number.' });

    const pageDir = path.join(packagesRoot, slug);
    // Covers both "a package with this id genuinely already exists on
    // disk" and "this process already registered it this session but
    // hasn't been restarted yet" -- same check tab-page-builder/server.js
    // and external-page-builder/server.js both use.
    if (fs.existsSync(pageDir) || pages.some((p) => p.id === slug)) {
      return res.status(409).json({ error: `A tracker named "${trackerLabel}" (id "${slug}") already exists. Pick a different name.` });
    }

    const apiBase = `/api/${slug}`;

    fs.mkdirSync(pageDir);
    fs.writeFileSync(path.join(pageDir, 'package.json'), buildPackageJson(slug, trackerLabel));
    fs.writeFileSync(path.join(pageDir, 'client.js'), buildClientJs(slug, trackerLabel, apiBase, rowNoun));
    fs.writeFileSync(path.join(pageDir, 'server.js'), buildServerJs(rowNoun));

    // Open the freshly-written data.db directly (same path its own
    // generated server.js will open on next require) and seed every typed
    // row/column, attributed to the admin who ran the builder -- no
    // silent/unattributed writes, same rule every other write on this
    // dashboard follows.
    const actor = { email: req.session.user.email, name: req.session.user.name };
    const trackerDb = createRolloutTrackerDb(path.join(pageDir, 'data.db'));
    for (const name of rowNames) trackerDb.addRow(name, actor);
    const existingKeys = new Set();
    for (const colLabel of columnLabels) {
      const baseKey = colLabel
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
      let key = baseKey;
      let n = 2;
      while (existingKeys.has(key)) key = `${baseKey}_${n++}`;
      existingKeys.add(key);
      trackerDb.addColumn(colLabel, key, actor);
    }

    // Makes it immediately servable AND mounts its own /api/<id> router --
    // see registerPage()'s own comment in registry.js.
    registerPage({
      dir: slug,
      root: pageDir,
      id: slug,
      label: trackerLabel,
      client: 'client.js',
      server: 'server.js',
    });

    // Filed straight into the "Trackers" category (creating it the first
    // time), not left at sidebar root like every other builder's output
    // here -- by request, so trackers accumulate in one place rather than
    // needing a manual drag every time, and so Hide Complete (see
    // rollout-tracker-server.js) has a "Trackers - Complete" to move a
    // finished one into that actually means something from day one.
    const tree = readNavLayout() || [];
    movePageToCategory(tree, slug, TRACKERS_CATEGORY_ID, TRACKERS_CATEGORY_LABEL);
    writeNavLayout(tree);

    res.json({ id: slug, label: trackerLabel });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
