const express = require('express');
const fs = require('fs');
const path = require('path');
const { matchesWildcard, getClient, listAll, excludeMonitoringAlerts, getPicklistLabels, resolveSingleCompany, todayAestKey, monthKeysWindow, monthLabel } = require('@dashboard/autotask-client');
const dattoRmm = require('@dashboard/datto-rmm/lib.js');
const { runIngest } = require('./ingest.js');

// Meeting Prep -- pulls every "reportable" chunk of data for one client
// into independent, selectable components, so a TAM can pick which ones
// to actually bring into a client meeting. Deliberately NOT built on or
// inside Check Client -- by request, Check Client is a reconciliation/
// consolidation tool (fixed sections, always shows everything for that
// client at once); this page is about curating a subset to present, which
// is a genuinely different job even though both are "look up one client
// across several systems."
//
// Two kinds of source feed the same generic `components` array (each
// entry carrying its own `kind`, see the client for how that's rendered):
// file-based report components (below), parsed from report PDFs each
// system's own scheduler/export produces (see the parser this data/
// folder's own README links to) into one JSON file per report per site,
// dropped into data/ using the naming convention documented there; and a
// couple of live sources -- Datto RMM devices and Autotask ticket counts,
// see "Live components" further down -- fetched fresh (Datto cached 20
// min, same convention as this dashboard's other Datto pulls) on every
// search. An earlier version of this page had a live Datto devices/alerts
// source in the old plain-table shape; that was removed by request, then
// Datto devices were reintroduced here in a new widget shape (by request,
// "like you previously did but as widgets"). More systems get added here
// the same way Dark Web Monitoring just was -- a new REPORT_TITLES/
// REPORT_SOURCES/REPORT_ORDER entry plus a new buildReportComponent()
// branch for a file-based one, or a new builder function pushed into the
// live half of the /components route below for anything live.

// A stable, URL/DOM-safe id for a report component -- real site names can
// contain spaces/punctuation, so this isn't just the raw name.
// Deterministic from the site name alone, so the same site always gets
// the same component id across searches/refreshes -- that's what lets the
// client keep a checkbox's "selected" state matched to the right
// component after a re-fetch.
const { slugify } = require('./slug.js');

// --------------------------------------------------------------------------
// File-based report components -- Datto RMM's own Report Center/Analytics
// has no REST API at all (confirmed against Datto's own docs), so these
// come from a different pipeline entirely: report PDFs generated by the
// account's existing Report Scheduler get parsed (see the parser this
// data/ folder's own README links to) into one JSON file per report per
// site, dropped in data/ using the naming convention documented there.
// This route just reads whatever's in data/ on every request -- it's a
// handful of small local JSON files, not worth caching -- and turns each
// one whose "site" field matches the search into a component, same shape
// as the live Datto RMM ones above. This data/ folder is also the exact
// place any future automated pickup (see data/README.md) writes into, so
// there's nothing here that needs reworking once that lands -- it just
// means files start showing up on their own instead of by hand.
const REPORT_DATA_DIR = path.join(__dirname, 'data');
const REPORT_IMAGES_DIR = path.join(__dirname, 'data', 'images');

// Exact, unaltered crops of the source report PDF -- pixels straight out of
// the PDF at 200dpi, no re-rendering, no re-interpretation -- alongside the
// structured data above, by request ("would it be possible to just give me
// each section of the reports in their exact format as they are without
// changing them"). Executive Summary has real named sub-sections in Datto's
// own layout (Summary, Asset Management, etc. -- see EXEC_SUMMARY_IMAGE_ORDER
// below), so it gets one image per section, including one stitched from two
// page crops where a section straddles a page break (Asset Management does,
// on the Kraftur sample). The other 4 report types have no sub-sections
// smaller than the whole report in Datto's layout, so they get one image per
// content page instead (cover page excluded). Filenames follow the same
// `<site-slug>--<kind>--...` convention as data/*.json, just with a third
// segment identifying the section/page -- see data/README.md.
const EXEC_SUMMARY_IMAGE_ORDER = ['summary', 'asset-management', 'patch-management', 'software-management', 'antivirus'];

function loadReportImages(kind, siteSlug) {
  const prefix = `${siteSlug}--${kind}--`;
  let filenames;
  try {
    filenames = fs.readdirSync(REPORT_IMAGES_DIR).filter((f) => f.startsWith(prefix) && f.endsWith('.png'));
  } catch {
    return []; // data/images/ doesn't exist yet, or nothing generated for this report -- no images, not an error
  }
  const entries = filenames.map((filename) => ({ id: filename.slice(prefix.length, -'.png'.length), filename }));
  if (kind === 'executive-summary') {
    entries.sort((a, b) => EXEC_SUMMARY_IMAGE_ORDER.indexOf(a.id) - EXEC_SUMMARY_IMAGE_ORDER.indexOf(b.id));
  } else {
    // "page-2", "page-3", ... -- sort numerically, not lexically (page-10
    // would otherwise sort before page-2).
    entries.sort((a, b) => (parseInt((a.id.match(/\d+/) || [0])[0], 10) || 0) - (parseInt((b.id.match(/\d+/) || [0])[0], 10) || 0));
  }
  return entries.map((e) => ({ id: e.id, url: `/api/meeting-prep/images/${e.filename}` }));
}

const REPORT_TITLES = {
  'executive-summary': 'Executive Summary Report',
  'device-activity': 'Device Activity Report',
  'device-health-summary': 'Device Health Summary Report',
  'device-monitor-status': 'Device Monitor Status Report',
  'device-storage': 'Device Storage Report',
  'hardware-lifecycle': 'Hardware Lifecycle Report',
  'network-audit': 'Network Audit Report',
  'open-monitor-alerts': 'Open Monitor Alerts Report',
  'patch-management-activity': 'Patch Management Activity Report',
  'patch-management-details': 'Patch Management Details Report',
  'patch-management-summary': 'Patch Management Summary Report',
  software: 'Software Report',
  'dark-web-monitoring': 'Dark Web Monitoring Report',
};

// Which system each report kind's data/*.json actually comes from -- shown
// as the card's source label. The first 5 are all Datto RMM Report Center;
// Dark Web Monitoring is the first report from a genuinely different
// system (Dark Web ID), proving out the "these and eventually others"
// pattern this whole data/ pipeline was built for -- a new kind plus an
// entry here and in REPORT_TITLES/REPORT_ORDER is the whole integration,
// nothing about loadFileReportComponents() itself needed to change.
const REPORT_SOURCES = {
  'executive-summary': 'Datto RMM Report',
  'device-activity': 'Datto RMM Report',
  'device-health-summary': 'Datto RMM Report',
  'device-monitor-status': 'Datto RMM Report',
  'device-storage': 'Datto RMM Report',
  'hardware-lifecycle': 'Datto RMM Report',
  'network-audit': 'Datto RMM Report',
  'open-monitor-alerts': 'Datto RMM Report',
  'patch-management-activity': 'Datto RMM Report',
  'patch-management-details': 'Datto RMM Report',
  'patch-management-summary': 'Datto RMM Report',
  software: 'Datto RMM Report',
  'dark-web-monitoring': 'Dark Web Monitoring',
};

// Fixed display order (Executive Summary first as the overview, the other
// Datto reports alphabetically by title, Dark Web Monitoring last as a
// different system) so cards don't reshuffle between searches/refreshes
// just because fs.readdirSync happened to return files in a different
// order. Device Activity, Device Monitor Status, Network Audit, Open
// Monitor Alerts, Patch Management Activity, Patch Management Details,
// and Software were all added in the same batch (by request, "process
// all files") -- each carries only a `summary` (counts), not full
// per-device detail, for the ones with a huge amount of per-device data
// (Device Activity's event log, Device Monitor Status's per-monitor
// readings, Software's per-device version list, Patch Management
// Activity/Details' per-patch listings) -- see this file's data/README.md
// and buildReportComponent() below for the same reasoning per kind.
const REPORT_ORDER = [
  'executive-summary',
  'device-activity',
  'device-health-summary',
  'device-monitor-status',
  'device-storage',
  'hardware-lifecycle',
  'network-audit',
  'open-monitor-alerts',
  'patch-management-activity',
  'patch-management-details',
  'patch-management-summary',
  'software',
  'dark-web-monitoring',
];

function buildReportComponent(kind, data) {
  const title = REPORT_TITLES[kind];
  if (!title) return null; // an unrecognised file in data/ -- skip it, don't fail the whole request over it
  const siteSlug = slugify(data.site || 'unknown');
  // Datto's reports all have a single createDate; Dark Web Monitoring has a
  // period range instead -- normalised to one display string here so every
  // component still has a createDate the card/detail header can show
  // without needing to know which shape produced it.
  const createDate = data.createDate || (data.periodStart && data.periodEnd ? `${data.periodStart} to ${data.periodEnd}` : null);
  const base = {
    id: `report-${kind}-${siteSlug}`,
    source: REPORT_SOURCES[kind] || 'Report',
    kind,
    title,
    // The real site name this component's own data came from (not the
    // search term that found it, which can be a wildcard matching more
    // than one client) -- lets the client group components by site, e.g.
    // for Selected Overview's own per-site tabs when a broad search
    // matched several clients at once.
    site: data.site || null,
    createDate,
    images: loadReportImages(kind, siteSlug),
    // The SharePoint webUrl of the original report PDF this component was
    // parsed from -- set on data/*.json by the parsing pipeline (see data/
    // README.md), null for anything parsed before this field existed.
    // Rendered by client.js's cardEl() as an "Original File" link at the
    // bottom of the card so a TAM can jump straight to the source document.
    sourceUrl: data.sourceUrl || null,
  };
  if (kind === 'executive-summary') {
    const summarySection = (data.sections || []).find((s) => s.kind === 'summary');
    return { ...base, stats: { overallScore: summarySection ? summarySection.overallScore : null }, sections: data.sections || [] };
  }
  if (kind === 'device-storage') {
    const drives = data.drives || [];
    return {
      ...base,
      stats: { driveCount: drives.length, criticalCount: drives.filter((d) => d.usedPercent != null && d.usedPercent >= 90).length },
      drives,
    };
  }
  if (kind === 'patch-management-summary') {
    const summary = data.summary || {};
    return {
      ...base,
      stats: { fullyPatched: summary['Fully Patched'] || 0, total: Object.values(summary).reduce((sum, n) => sum + (n || 0), 0) },
      summary,
      devices: data.devices || [],
    };
  }
  if (kind === 'device-health-summary') {
    const summary = data.summary || {};
    return { ...base, stats: { checksPassed: summary.checksPassed, checksFailed: summary.checksFailed }, summary, devices: data.devices || [] };
  }
  if (kind === 'hardware-lifecycle') {
    const bands = data.bands || [];
    const countOf = (id) => (bands.find((b) => b.id === id) || { devices: [] }).devices.length;
    return {
      ...base,
      stats: { within12: countOf('within-12-months'), months12to24: countOf('12-24-months'), plus24: countOf('24-plus-months') },
      summary: data.summary || {},
      bands,
    };
  }
  if (kind === 'network-audit') {
    return { ...base, stats: { managedCount: data.managedCount || 0, unmanagedCount: data.unmanagedCount || 0 }, devices: data.devices || [] };
  }
  if (kind === 'open-monitor-alerts') {
    const devices = data.devices || [];
    return {
      ...base,
      stats: { totalOpen: devices.reduce((n, d) => n + (d.total || 0), 0), devicesWithAlerts: devices.filter((d) => (d.total || 0) > 0).length },
      devices,
    };
  }
  // Device Activity, Device Monitor Status, Software, and the two Patch
  // Management event-log reports all carry a huge amount of per-device
  // detail in the source PDF (a month of activity events, a live monitor
  // reading per device, every installed software version per device, a
  // patch-by-patch table per device) -- by request, these only get a
  // `summary` (counts) here, not the full per-device breakdown, so a
  // client with many devices doesn't blow this up into an unreadable
  // card. The counts themselves are computed once, at parse time, and
  // stored directly in data/*.json's own `summary` -- this just passes
  // them through.
  if (kind === 'device-activity') {
    return { ...base, stats: { failedEvents: (data.summary || {}).failedEvents || 0 }, summary: data.summary || {} };
  }
  if (kind === 'device-monitor-status') {
    return { ...base, stats: { totalMonitorEntries: (data.summary || {}).totalMonitorEntries || 0 }, summary: data.summary || {} };
  }
  if (kind === 'software') {
    return { ...base, stats: { distinctTitles: (data.summary || {}).distinctTitles || 0 }, summary: data.summary || {} };
  }
  if (kind === 'patch-management-activity') {
    return { ...base, stats: { totalPatchInstallEvents: (data.summary || {}).totalPatchInstallEvents || 0 }, summary: data.summary || {} };
  }
  if (kind === 'patch-management-details') {
    return { ...base, stats: { totalPatchesListed: (data.summary || {}).totalPatchesListed || 0 }, summary: data.summary || {} };
  }
  if (kind === 'dark-web-monitoring') {
    const summary = data.summary || {};
    return {
      ...base,
      stats: { totalCompromises: summary.totalCompromises || 0, customerAverage: (data.benchmark || {}).customerAverageCompromises || 0 },
      summary,
      benchmark: data.benchmark || {},
      monitoring: data.monitoring || {},
      organizationalCompromises: data.organizationalCompromises || [],
      breaches: data.breaches || { totalCompromises: 0, breaches: [] },
    };
  }
  return null;
}

// data/<client-slug>/<date>/<kind>.json -- one folder per client, one
// dated subfolder per report run, mirroring the SharePoint Processed
// folder's own <Client Name>/<date>/ shape 1:1 (by request, so the two
// stay easy to reason about together). Replaced the original flat
// data/<slug>--<kind>.json (silently overwritten on every re-run) once
// keeping history actually mattered -- see data/README.md. `images/`
// lives alongside the client folders in this same directory (its own
// unrelated flat naming scheme, untouched by this) -- skipped here by
// name, not by "is it a real client", since a client could in principle
// be named something that only coincidentally isn't "images".
function loadFileReportComponents(siteTerm) {
  let clientDirs;
  try {
    clientDirs = fs
      .readdirSync(REPORT_DATA_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name !== 'images');
  } catch {
    return []; // data/ doesn't exist yet on a fresh checkout -- no report components, not an error
  }
  const components = [];
  for (const clientDir of clientDirs) {
    const clientPath = path.join(REPORT_DATA_DIR, clientDir.name);
    let dateDirs;
    try {
      dateDirs = fs.readdirSync(clientPath, { withFileTypes: true }).filter((d) => d.isDirectory());
    } catch {
      continue;
    }
    // Newest date first (plain string sort works here since the folder
    // name is always YYYY-MM-DD) -- the first time a given `kind` shows
    // up below is therefore always its most recent run, so only ONE
    // snapshot per kind ever becomes a component. Older dates stay on
    // disk for history, just not surfaced on this page (yet -- see the
    // README's own "Not yet built" for a future trend-over-time view).
    dateDirs.sort((a, b) => b.name.localeCompare(a.name));
    const seenKinds = new Set();
    for (const dateDir of dateDirs) {
      const datePath = path.join(clientPath, dateDir.name);
      let filenames;
      try {
        filenames = fs.readdirSync(datePath).filter((f) => f.endsWith('.json'));
      } catch {
        continue;
      }
      for (const filename of filenames) {
        const kind = filename.replace(/\.json$/, '');
        if (seenKinds.has(kind)) continue; // already have this kind's LATEST run from a newer date folder
        let data;
        try {
          data = JSON.parse(fs.readFileSync(path.join(datePath, filename), 'utf8'));
        } catch (err) {
          console.error(`Meeting Prep: failed to read data/${clientDir.name}/${dateDir.name}/${filename}:`, err.message);
          continue;
        }
        // Marked seen regardless of whether it matches the search below --
        // every file under one client folder describes that SAME client,
        // so if its newest run doesn't match the search term, no older
        // run of the same kind should surface either.
        seenKinds.add(kind);
        if (!data.site || !matchesWildcard(data.site, siteTerm)) continue;
        const component = buildReportComponent(kind, data);
        if (component) components.push(component);
      }
    }
  }
  components.sort((a, b) => REPORT_ORDER.indexOf(a.kind) - REPORT_ORDER.indexOf(b.kind));
  return components;
}

// Same walk as loadFileReportComponents() above, but for EVERY client
// folder at once and with no site-name filter -- used by Service Actions
// (a separate page) to run the recommendations engine across the whole
// client base in one request. Kept here rather than duplicated because
// it's the exact same "latest date wins per kind" logic, just without the
// matchesWildcard() narrowing loadFileReportComponents() applies. Returns
// one entry per client folder that has at least one component, `site`
// taken from whichever file supplied it (they're expected to agree within
// one client folder -- see data/README.md's own note on this) falling
// back to a prettified version of the folder name on the rare chance no
// file inside it has a `site` field at all.
function loadAllFileReportComponentsByClient() {
  let clientDirs;
  try {
    clientDirs = fs
      .readdirSync(REPORT_DATA_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name !== 'images');
  } catch {
    return [];
  }
  const results = [];
  for (const clientDir of clientDirs) {
    const clientPath = path.join(REPORT_DATA_DIR, clientDir.name);
    let dateDirs;
    try {
      dateDirs = fs.readdirSync(clientPath, { withFileTypes: true }).filter((d) => d.isDirectory());
    } catch {
      continue;
    }
    dateDirs.sort((a, b) => b.name.localeCompare(a.name));
    const seenKinds = new Set();
    const components = [];
    let site = null;
    for (const dateDir of dateDirs) {
      const datePath = path.join(clientPath, dateDir.name);
      let filenames;
      try {
        filenames = fs.readdirSync(datePath).filter((f) => f.endsWith('.json'));
      } catch {
        continue;
      }
      for (const filename of filenames) {
        const kind = filename.replace(/\.json$/, '');
        if (seenKinds.has(kind)) continue;
        let data;
        try {
          data = JSON.parse(fs.readFileSync(path.join(datePath, filename), 'utf8'));
        } catch (err) {
          console.error(`Meeting Prep: failed to read data/${clientDir.name}/${dateDir.name}/${filename}:`, err.message);
          continue;
        }
        seenKinds.add(kind);
        if (!site && data.site) site = data.site;
        const component = buildReportComponent(kind, data);
        if (component) components.push(component);
      }
    }
    if (components.length === 0) continue;
    components.sort((a, b) => REPORT_ORDER.indexOf(a.kind) - REPORT_ORDER.indexOf(b.kind));
    results.push({
      client: site || clientDir.name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      components,
    });
  }
  results.sort((a, b) => a.client.localeCompare(b.client));
  return results;
}

// --------------------------------------------------------------------------
// Live components -- fetched fresh from each system's own API on every
// search, rather than read from data/. Each builder below is wrapped
// individually in the /components route (Promise.all + its own try/catch),
// same "one broken card doesn't take down the others" reasoning
// datto-rmm/lib.js's own getOverview() already uses for its filter cards --
// a Datto outage shouldn't hide the file-based reports, and vice versa.

// Datto RMM devices, as widgets -- by request ("From Datto RMM like you
// previously did but as widgets like this"), reusing Check Client's own
// Section 5 pattern (own 20-minute in-process cache via getAllDevices(),
// matched against Datto's own siteName with matchesWildcard()) rather than
// calling datto-rmm/server.js (that package's own router/cache is for its
// account-wide overview page, a different shape -- see check-client's own
// comment on this same choice).
const DATTO_CACHE_TTL_MS = 20 * 60 * 1000; // 20 min -- same convention as Datto RMM's own overview cache and Check Client's Section 5
let dattoDevicesCache = null; // { data, expiresAt }
let dattoDevicesInFlight = null;
async function getCachedDattoDevices(force) {
  if (!force && dattoDevicesCache && Date.now() < dattoDevicesCache.expiresAt) return dattoDevicesCache.data;
  if (!dattoDevicesInFlight) {
    dattoDevicesInFlight = dattoRmm
      .getAllDevices()
      .then((data) => {
        dattoDevicesCache = { data, expiresAt: Date.now() + DATTO_CACHE_TTL_MS };
        return data;
      })
      .finally(() => {
        dattoDevicesInFlight = null;
      });
  }
  return dattoDevicesInFlight;
}

// "Seen <7 days" / "7-30 days" / "not seen 30+ days" -- the same 3-band
// check-in-freshness read the screenshot's KPI tiles and segmented bar both
// use. `lastSeen` missing entirely (never confirmed against a real payload
// to be impossible, just not seen in testing) gets its own 'unknown' bucket
// rather than being silently folded into "stale" -- a device Datto has
// simply never reported a lastSeen for isn't the same claim as "not seen in
// 30+ days".
function classifyFreshness(lastSeenIso) {
  if (!lastSeenIso) return 'unknown';
  const ageDays = (Date.now() - new Date(lastSeenIso).getTime()) / 86400000;
  if (!Number.isFinite(ageDays)) return 'unknown';
  if (ageDays < 7) return 'recent';
  if (ageDays < 30) return 'ageing';
  return 'stale';
}

function buildDattoLiveDevicesComponent(siteTerm, allDevices, asOf) {
  const devices = allDevices.filter((d) => matchesWildcard(d.site, siteTerm));
  // No matching devices -- omit the card entirely rather than show an
  // empty one, same convention loadFileReportComponents() already follows
  // for a site with no report files.
  if (devices.length === 0) return null;

  const buckets = { recent: 0, ageing: 0, stale: 0, unknown: 0 };
  const byType = new Map();
  const rows = [];
  for (const d of devices) {
    const freshness = classifyFreshness(d.lastSeen);
    buckets[freshness] += 1;
    const type = d.deviceType || 'Unknown';
    byType.set(type, (byType.get(type) || 0) + 1);
    rows.push({
      id: d.id,
      hostname: d.hostname,
      type,
      lastSeen: d.lastSeen,
      freshness,
      online: d.online,
      lastUser: d.lastUser,
    });
  }
  rows.sort((a, b) => (a.hostname || '').localeCompare(b.hostname || ''));

  // "Core Resources" was hardcoded as a literal title at first (lifted
  // straight from the reference screenshot's own dashboard heading, which
  // -- as it turns out -- was itself a real client's own Datto dashboard,
  // not a generic mockup) -- a real bug, confirmed by request ("Datto RMM
  // tile is called Core Resources regardless of the chosen and reported
  // client"): every client's card read identically, which is actively
  // confusing when switching between clients in one session.
  //
  // First attempted fix got this WRONG in a worse way: it kept the literal
  // "Core Resources" text and just appended the real site name after it
  // (`Core Resources -- ${siteNames[0]}`), so a search for e.g. "Flow
  // Financial Planning" rendered the title "Core Resources -- Flow
  // Financial Planning" -- confirmed by a screenshot Amber sent showing
  // exactly that, on a real client that is NOT called Core Resources. That
  // read as two different clients' data being mixed together on one card,
  // which is a much worse failure mode than the original bug (a static
  // wrong label) even though no data was actually wrong underneath it --
  // this was purely a display string mistake, but a bad one to make on a
  // page used live in front of clients. Correct fix: the hardcoded string
  // is gone entirely, the title is ONLY the real matched site name(s) --
  // Datto's own siteName off the matched devices themselves, not the raw
  // siteTerm search text (which can be a wildcard like "Kraftur*" rather
  // than a clean name). Normally every matched device agrees on one real
  // site name; the rare case where a broad wildcard spans more than one is
  // called out explicitly rather than just picking one and hiding the
  // ambiguity.
  const siteNames = [...new Set(devices.map((d) => d.site).filter(Boolean))];
  const title = siteNames.length === 1 ? siteNames[0] : siteNames.length > 1 ? `${siteNames.length} sites matched` : 'Live Devices';

  return {
    id: `live-datto-devices-${slugify(siteTerm)}`,
    source: 'Datto RMM (live)',
    kind: 'datto-live-devices',
    title,
    // null when this one component's own devices span more than one real
    // site (same ambiguous-wildcard case `title` above already calls out)
    // -- same reasoning as buildReportComponent()'s own `site` field, but
    // there's no single real value to give here in that case.
    site: siteNames.length === 1 ? siteNames[0] : null,
    createDate: asOf,
    images: [],
    stats: { total: devices.length, notSeenStale: buckets.stale },
    summary: {
      total: devices.length,
      seenRecent: buckets.recent,
      seenAgeing: buckets.ageing,
      notSeenStale: buckets.stale,
      unknown: buckets.unknown,
    },
    byType: [...byType.entries()].map(([type, count]) => ({ type, count })).sort((a, b) => b.count - a.count),
    // See datto-rmm/lib.js's own mapDeviceSummary() comment -- the
    // deviceType field this breakdown is built from hasn't been confirmed
    // against a real payload from this account yet. Carried through here so
    // the client can show an honest caveat next to the widget rather than
    // presenting it as settled.
    deviceTypeConfirmed: false,
    devices: rows,
  };
}

// Autotask ticket counts -- by request ("ticket counts by Priority, Open
// and closed in the month... just getting something in there, we will
// elaborate on this one later"), so deliberately minimal: current open
// tickets grouped by priority, plus how many were opened and closed in the
// current AEST calendar month. "Closed" reuses Completed Tickets' own
// confirmed real definition (status 5 "Complete" by completedDate, UNIONed
// with status 20 "Billing - Contract" by resolvedDateTime -- see that
// package's own server.js comment for why status 20 needs the different
// date field). "Opened" is simply createDate falling in the same month --
// not independently confirmed against any existing page since nothing else
// on this dashboard counts tickets opened-in-a-month, so treat that one
// figure as the more provisional of the two if it's ever checked against
// Autotask's own UI count. Monitoring-alert tickets (issueType 14) are
// excluded from every count here, same as everywhere else on this
// dashboard that counts tickets, and for the same confirmed reason
// (excludeMonitoringAlerts()'s own comment).
async function buildAutotaskTicketsComponent(client, siteTerm) {
  const resolved = await resolveSingleCompany(client, siteTerm, null);
  const base = {
    id: `live-autotask-tickets-${slugify(siteTerm)}`,
    source: 'Autotask (live)',
    kind: 'autotask-tickets',
    title: 'Ticket Summary',
    createDate: null,
    images: [],
  };
  if (resolved.status !== 'ok') {
    // Not folded silently into "no data" -- a client search term that
    // doesn't resolve to exactly one Autotask company is a real signal
    // worth surfacing (wrong/ambiguous search term), not a missing-config
    // state like Datto credentials being absent.
    return { ...base, stats: null, resolveStatus: resolved.status, matches: resolved.matches || [] };
  }
  const company = resolved.company;
  const companyID = company.id;

  const currentMonthKey = todayAestKey().slice(0, 7);
  const { windowStart, windowEnd } = monthKeysWindow([currentMonthKey]);

  const [openTicketsRaw, completedRaw, billingRaw, openedThisMonthRaw, priorityLabels] = await Promise.all([
    listAll(client.tickets, [
      { op: 'eq', field: 'companyID', value: companyID },
      { op: 'notExist', field: 'completedDate' },
    ]),
    listAll(client.tickets, [
      { op: 'eq', field: 'companyID', value: companyID },
      { op: 'eq', field: 'status', value: 5 },
      { op: 'gte', field: 'completedDate', value: windowStart },
      { op: 'lt', field: 'completedDate', value: windowEnd },
    ]),
    listAll(client.tickets, [
      { op: 'eq', field: 'companyID', value: companyID },
      { op: 'eq', field: 'status', value: 20 },
      { op: 'gte', field: 'resolvedDateTime', value: windowStart },
      { op: 'lt', field: 'resolvedDateTime', value: windowEnd },
    ]),
    listAll(client.tickets, [
      { op: 'eq', field: 'companyID', value: companyID },
      { op: 'gte', field: 'createDate', value: windowStart },
      { op: 'lt', field: 'createDate', value: windowEnd },
    ]),
    getPicklistLabels(client.tickets, 'priority'),
  ]);

  const openTickets = excludeMonitoringAlerts(openTicketsRaw);
  const closedThisMonth = excludeMonitoringAlerts([...completedRaw, ...billingRaw]);
  const openedThisMonth = excludeMonitoringAlerts(openedThisMonthRaw);

  const byPriorityMap = new Map();
  for (const t of openTickets) {
    const label = priorityLabels.get(t.priority) || `Priority ${t.priority}`;
    byPriorityMap.set(label, (byPriorityMap.get(label) || 0) + 1);
  }

  return {
    ...base,
    resolveStatus: 'ok',
    companyName: company.companyName,
    monthLabel: monthLabel(currentMonthKey),
    stats: { openCount: openTickets.length, openedThisMonth: openedThisMonth.length, closedThisMonth: closedThisMonth.length },
    byPriority: [...byPriorityMap.entries()].map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count),
  };
}

const router = express.Router();

// Serves data/images/*.png at /api/meeting-prep/images/<filename> -- the
// urls loadReportImages() hands back above. Plain express.static, same as
// the shell's own public/ folder -- these are read-only report crops, not
// user-controlled paths, so no extra checking needed beyond what
// express.static already does.
router.use('/images', express.static(REPORT_IMAGES_DIR));

// A caught/rejected promise already can't take the whole response down --
// every live source below is wrapped in its own try/catch. But a live
// source that's gone SLOW instead of failing outright (stuck retrying
// against a rate limit, a network stall, whatever) is a sharper risk:
// `await` just waits, so a live source that never settles at all would
// hold up the entire response indefinitely -- including the file-based
// report components above, which are already read from disk and sitting
// ready to send well before any live source is even called. That's what a
// real incident traced back to here: repeated Autotask 429s with nothing
// bounding how long the underlying client's retry might take (see
// data/README.md's neighbouring note, or ask Amber/Claude for the
// incident writeup) turned one rate-limited ticket query into the whole
// page looking like it had silently lost every report. Every live source
// gets a hard timeout for exactly this reason -- not just the one that's
// already caused a problem, since a slow Datto RMM call deserves the same
// guarantee for the same reason: nothing live is allowed to block data
// that was never dependent on it in the first place.
const LIVE_SOURCE_TIMEOUT_MS = 8000;
function withTimeout(promise, label) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`${label} timed out after ${LIVE_SOURCE_TIMEOUT_MS}ms`)), LIVE_SOURCE_TIMEOUT_MS);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

// One route, returning a generic `components` array (each with its own
// `kind`) rather than separate per-source endpoints -- deliberately, so
// adding a second source later means pushing more entries into the same
// array/shape, not a client-side rewrite.
router.get('/components', async (req, res) => {
  // This endpoint's whole point is live/current data (device check-ins,
  // ticket counts, whatever's newest in data/) -- explicitly uncacheable,
  // so a browser never serves a stale response for a repeated search
  // instead of hitting the network again. Belt-and-braces with the
  // matching `cache: 'no-store'` on the client's own fetch() call.
  res.set('Cache-Control', 'no-store');
  const siteTerm = (req.query.client || '').trim();
  if (!siteTerm) return res.status(400).json({ error: 'Query param "client" is required.' });
  try {
    const asOf = new Date().toISOString();
    // File-based report components are read from disk synchronously, right
    // here, before any live source is even touched -- nothing below this
    // line can ever prevent these from being computed. withTimeout() above
    // is what guarantees they also can't be prevented from being SENT.
    const components = loadFileReportComponents(siteTerm);

    // TEMPORARILY DISABLED (2026-09-23): the live Autotask ticket-counts
    // component was hitting Autotask's own API rate limit (repeated 429s
    // logged at the exact point a client-facing incident was reported).
    // Pulled out as an immediate stabilisation; re-enable (wrapped in
    // withTimeout(), same as Datto below) only after confirming with
    // Autotask why 5 parallel ticket queries per search are enough to trip
    // a 429 -- a per-account limit shared with every other page on this
    // dashboard, not something this route can just retry its way past.
    const dattoComponent = await (async () => {
      if (!dattoRmm.hasDattoCredentials()) return null;
      try {
        const allDevices = await withTimeout(getCachedDattoDevices(req.query.refresh === 'true'), 'Datto RMM devices');
        return buildDattoLiveDevicesComponent(siteTerm, allDevices, asOf);
      } catch (err) {
        console.error('Meeting Prep: Datto RMM live devices failed:', err.message);
        return null;
      }
    })();
    if (dattoComponent) components.push(dattoComponent);
    // const ticketsComponent = ... -- see comment above; disabled for now.

    res.json({ connected: true, asOf, siteTerm, components });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

// Bulk, all-clients equivalent of /components -- used by the separate
// Service Actions page to run the same rules-based recommendations across
// every client at once. File-based only, deliberately -- no live
// Datto/Autotask calls fanned out across 28 clients, both because the
// recommendations engine itself never looks at live data anyway (see
// meeting-prep-recommendations.js's own header) and because Autotask
// ticket counts have already tripped a real rate limit once at even the
// one-client-at-a-time volume this page's own /components route uses (see
// the comment above) -- a bulk version of that same call would be a much
// worse version of the same problem.
router.get('/all-file-components', (req, res) => {
  res.set('Cache-Control', 'no-store');
  try {
    const byClient = loadAllFileReportComponentsByClient();
    res.json({ asOf: new Date().toISOString(), clients: byClient });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

// "Process Incoming Reports" button, by request -- mirrors Contract
// Checks' own POST /sync (its own "Check for more Orders in IM" button):
// runs ingest.js's runIngest() and returns its full result (processed/
// ignored counts plus the needsAttention list, so a manual click surfaces
// exactly what a scheduled-task run would only leave in the log). See
// ingest.js's own top comment for the full pipeline this runs.
router.post('/ingest', async (req, res) => {
  try {
    const result = await runIngest();
    res.json(result);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
