import { createTabbedPageMount } from '/tab-page-client.js';

export const id = "time-reporting-tabs";
export const label = "Time reporting";

// Generated by Tab Page Builder -- see @dashboard/shell/tab-page-client.js
// for the actual tabbed-page mechanism, shared by every tabbed page on
// this dashboard.
export const mount = createTabbedPageMount({
  id,
  label,
  apiBase: "/api/time-reporting-tabs",
  defaultTabs: [{"id":"times","label":"Time Summaries"}],
});
